FROM golang:1.25-alpine AS builder
WORKDIR /app


COPY go.mod ./
RUN go mod download

COPY . .


RUN CGO_ENABLED=0 GOOS=linux go build -o /app/dumper ./cmd


FROM alpine:3.20

WORKDIR /app


RUN apk add --no-cache \
    postgresql-client \
    ca-certificates \
    tzdata

RUN mkdir -p /dumps

COPY --from=builder /app/dumper /app/dumper

EXPOSE 8007

ENTRYPOINT ["/app/dumper"]
